services:
  server:
    image: trentshailer/investible-webserver:1.0.13
    env_file:
      - ./.env
    ports:
      - 4008:8080
    depends_on:
      - database
    restart: always
  database:
    image: postgres:13-alpine
    env_file:
      - ./.env
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
